/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gilbertopsantosjr' at '06/02/17 18:20' with Gradle 3.2
 *
 * @author gilbertopsantosjr, @date 06/02/17 18:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
