package br.com.cadmus;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gilbertopsantosjr' at '06/02/17 18:20' with Gradle 3.2
 *
 * @author gilbertopsantosjr, @date 06/02/17 18:20
 */

import org.gradle.api.DefaultTask;
import org.gradle.api.resources.ResourceHandler;
import org.gradle.api.tasks.TaskAction;
import org.gradle.api.tasks.TaskExecutionException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Map;

public class CadmusTask extends DefaultTask {

    private final Logger log = LoggerFactory.getLogger(getClass());

    @TaskAction
    public void samplePluginTasks() throws TaskExecutionException {
        log.info("Starting  sample task");
        try {
            System.out.println(" Cadmus called ");

            final Map<String, ?> properties = getProject().getProperties();
            final ResourceHandler resourceHandler = getProject().getResources();
            resourceHandler.getText();

            final TemplateDir extension = getProject().getExtensions().findByType(TemplateDir.class);
            final String filePath = extension.getFilePath();

            log.debug("Sample file path is: {}", filePath);
            log.info("Successfully completed sample Task");
        } catch (final Exception e) {
            log.error("Exception occured while processing sampleTask", e);
            throw new TaskExecutionException(this, e);
        }
    }


}